# Generated by Django 4.2.5 on 2023-09-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claveFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClave', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=16)),
                ('confirmarClave', models.CharField(max_length=16)),
                ('pista', models.CharField(max_length=10)),
            ],
        ),
    ]
