# Generated by Django 4.2.5 on 2023-09-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crear_elementos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logins',
        ),
    ]
