# Generated by Django 4.2.5 on 2023-09-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_elementos', '0002_rename_login_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIdentificacion', models.CharField(max_length=15)),
                ('numero', models.IntegerField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('fechaExpedicion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('nota', models.CharField(max_length=255)),
            ],
        ),
    ]
